version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: katekatekatem/foodgram_backend
    env_file: ./.env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db

  frontend:
    image: katekatekatem/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: katekatekatem/foodgram_gateway
    ports:
      - 7001:80
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/api/docs/
      - static:/backend_static
      - media:/media
    depends_on:
      - backend
      - frontend
