# Generated by Django 3.2 on 2023-08-26 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230826_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_to_buy', to='recipes.recipe')),
                ('user_to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_buy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_to_buy__username',),
            },
        ),
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('user_to_buy', 'recipe_to_buy'), name='unique_user_to_buy&recipe_to_buy'),
        ),
    ]
